[package]
name = "grid_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy = "0.0.302"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
